### ISSUE TITLE
Flags are not visible on web

### ISSUE THREAD

**Issue by OmarThinks** [kuasha420/react-native-paper-phone-number-input#2]
Thanks a lot for creating this awesome package.

But if you can display the flags on web that will be amazing.

**Comment by kuasha420** [comment]
Hi, the flags are actually unicode emojis and should render on all modern system. Can you check if the flags are loading on the `example` app by cloning the repo and running `yarn && yarn example web`?

**Comment by OmarThinks** [comment]
Hello, @kuasha420 ! 👋
I tried.
And the error is also there.
😁

**Comment by kuasha420** [comment]
Hello :wave: 

Can you tell me which OS and Browser are you using? I can see everything Fine in Firefox and Chrome in Linux. 

I'm assuming your system doesn't come with a Emoji font installed that has the flags. If you provide further info, I can try and see if we can include a web font for compat reasons. 

Cheers. 

![Screenshot_20240710_160110](https://github.com/kuasha420/react-native-paper-phone-number-input/assets/6187401/378cc5ed-a793-49d9-b287-6150c4f708a3)

**Comment by OmarThinks** [comment]
Hello, @kuasha420  ! 👋
Thanks a lot for your patience and cooperation.
I'm more than grateful. 😁🫡✅💯

OS: Windows
Browser: Chrome and Edge
Note: (I just found out that the Flags are visible on Firefox)

![Screenshot 2024-07-12 115123](https://github.com/user-attachments/assets/67778600-4843-4a00-9cbc-bbb364fd0e8a)

**Comment by kuasha420** [comment]
Hi @OmarThinks. Thanks for providing the details. :muscle: 

I've done some research on this, and yes, Microsoft intentionally doesn't include emoji flags in their emoji font. Common Microsoft L there. 

Firefox gets around this by bundling `Twemoji` font themselves. That's why it work in Firefox even in Windows but not Chromium Based browsers. 

To get around this, I'd recommend using [this](https://github.com/talkjs/country-flag-emoji-polyfill) polyfill. Try it out and let me know if this works. I don't have a Windows machine at hand to test this.

If this solves the issue, I'll add a note about this in the Readme. 

Cheers. :heart:

**Comment by kuasha420** [comment]
Hi @OmarThinks :wave: 

Can you try #5 PR and see if this fixes the issue in Windows for you? You also need to follow the documentation for Windows [here](https://github.com/kuasha420/react-native-paper-phone-number-input/tree/flag-on-windows?tab=readme-ov-file#add-support-for-web). 

Cheers.
